/* 320개의 단어 */

const initialWords = [
    { english: "benevolent", korean: "자비로운", koreanMeaning: "친절하고 너그러운" },
    { english: "ubiquitous", korean: "어디에나 있는", koreanMeaning: "어디에나 존재하거나 나타나는" },
    { english: "ephemeral", korean: "덧없는", koreanMeaning: "지속 시간이 매우 짧은, 덧없는" },
    { english: "gregarious", korean: "사교적인", koreanMeaning: "사람들과 어울리기 좋아하는, 사교적인" },
    { english: "ostentatious", korean: "과시하는", koreanMeaning: "허세 부리는, 과시하는" },
    { english: "perfunctory", korean: "성의 없는", koreanMeaning: "열의 없이 형식적으로 하는, 피상적인" },
    { english: "propensity", korean: "성향", koreanMeaning: "강한 성향, 경향" },
    { english: "quixotic", korean: "돈키호테적인", koreanMeaning: "비현실적인, 이상주의적인" },
    { english: "recalcitrant", korean: "저항하는", koreanMeaning: "권위에 저항하는, 다루기 힘든" },
    { english: "serendipity", korean: "뜻밖의 행운", koreanMeaning: "뜻밖의 즐거움이나 유익한 발견" },
    { english: "taciturn", korean: "말없는", koreanMeaning: "말수가 적은, 과묵한" },
    { english: "vacillate", korean: "망설이다", koreanMeaning: "결정을 못하고 흔들리다" },
    { english: "ameliorate", korean: "개선하다", koreanMeaning: "개선시키다, 더 좋게 만들다" },
    { english: "capricious", korean: "변덕스러운", koreanMeaning: "변덕스러운, 예측 불가능한" },
    { english: "deleterious", korean: "해로운", koreanMeaning: "해로운, 유해한" },
    { english: "equanimity", korean: "평정", koreanMeaning: "마음의 평정, 침착함" },
    { english: "fastidious", korean: "꼼꼼한", koreanMeaning: "세심한, 까다로운" },
    { english: "ignominious", korean: "수치스러운", koreanMeaning: "수치스러운, 불명예스러운" },
    { english: "juxtaposition", korean: "병치", koreanMeaning: "대조적인 것을 나란히 놓음" },
    { english: "kudos", korean: "영광", koreanMeaning: "칭찬, 영광" },
    { english: "aberration", korean: "일탈", koreanMeaning: "정상에서 벗어난 것" },
    { english: "cacophony", korean: "불협화음", koreanMeaning: "불쾌한 소리의 조합" },
    { english: "dearth", korean: "부족", koreanMeaning: "어떤 것의 부족이나 결핍" },
    { english: "eclectic", korean: "다방면의", koreanMeaning: "다양한 원천에서 가져온" },
    { english: "fathom", korean: "헤아리다", koreanMeaning: "어떤 것을 이해하다" },
    { english: "garner", korean: "모으다", koreanMeaning: "정보나 지지를 모으다" },
    { english: "haughty", korean: "오만한", koreanMeaning: "거만하거나 오만한 태도" },
    { english: "impeccable", korean: "흠 잡을 데 없는", koreanMeaning: "결점이 없는, 완벽한" },
    { english: "jocose", korean: "우스꽝스러운", koreanMeaning: "농담을 잘 하는, 익살스러운" },
    { english: "kinetic", korean: "운동의", koreanMeaning: "움직임과 관련된" },
    { english: "lament", korean: "애도하다", koreanMeaning: "슬픔이나 실망을 표현하다" },
    { english: "magnanimous", korean: "관대한", koreanMeaning: "다른 사람에게 관대하고 너그러운" },
    { english: "nefarious", korean: "사악한", koreanMeaning: "사악하거나 범죄적인" },
    { english: "obfuscate", korean: "혼란시키다", koreanMeaning: "혼란스럽게 하거나 불분명하게 만들다" },
    { english: "palpable", korean: "감지할 수 있는", koreanMeaning: "만질 수 있거나 명백히 감지할 수 있는" },
    { english: "quandary", korean: "곤경", koreanMeaning: "어려운 상황이나 딜레마" },
    { english: "rapport", korean: "친밀한 관계", koreanMeaning: "사람들 사이의 조화로운 관계" },
    { english: "sallow", korean: "병색이 짙은", koreanMeaning: "병적으로 노란색이나 회색빛을 띠는" },
    { english: "tantamount", korean: "마찬가지의", koreanMeaning: "어떤 것과 동등하거나 마찬가지인" },
    { english: "ubiquitous", korean: "어디에나 있는", koreanMeaning: "어디에나 존재하거나 나타나는" },
    { english: "verbose", korean: "장황한", koreanMeaning: "말이 많거나 장황한" },
    { english: "wistful", korean: "애석해하는", koreanMeaning: "향수나 슬픔을 느끼는" },
    { english: "xenophobia", korean: "외국인 혐오증", koreanMeaning: "외국인에 대한 강한 두려움이나 싫어함" },
    { english: "yield", korean: "생산하다", koreanMeaning: "생산하다, 양보하다" },
    { english: "zephyr", korean: "서풍", koreanMeaning: "온화한 서풍" },
    { english: "arduous", korean: "힘든", koreanMeaning: "매우 힘들고 고된" },
    { english: "blasphemy", korean: "신성 모독", koreanMeaning: "신성한 것에 대한 불경한 언사나 행동" },
    { english: "chicanery", korean: "속임수", koreanMeaning: "교활한 속임수나 계략" },
    { english: "decimate", korean: "대량 살육하다", koreanMeaning: "많은 부분을 파괴하거나 죽이다" },
    { english: "enervate", korean: "기력을 잃게 하다", koreanMeaning: "기력을 약화시키거나 에너지를 고갈시키다" },
    { english: "finesse", korean: "솜씨", koreanMeaning: "섬세한 기술이나 수완" },
    { english: "garrulous", korean: "수다스러운", koreanMeaning: "매우 수다스러운" },
    { english: "herculean", korean: "매우 힘든", koreanMeaning: "엄청난 노력이나 힘이 필요한" },
    { english: "impetuous", korean: "충동적인", koreanMeaning: "충동적으로 행동하는" },
    { english: "juxtapose", korean: "나란히 놓다", koreanMeaning: "대조를 위해 두 가지를 나란히 놓다" },
    { english: "languid", korean: "나른한", koreanMeaning: "활기 없거나 힘이 없는" },
    { english: "maudlin", korean: "감상적인", koreanMeaning: "지나치게 감상적인" },
    { english: "nonchalant", korean: "무심한", koreanMeaning: "태연하거나 무관심한" },
    { english: "obsequious", korean: "아첨하는", koreanMeaning: "지나치게 아첨하거나 비굴한" },
    { english: "parsimonious", korean: "인색한", koreanMeaning: "매우 인색하거나 검소한" },
    { english: "querulous", korean: "불평하는", koreanMeaning: "불평하거나 투덜거리는 경향이 있는" },
    { english: "replete", korean: "가득 찬", koreanMeaning: "가득 차 있거나 풍부한" },
    { english: "sanctimonious", korean: "독선적인", koreanMeaning: "도덕적으로 우월한 척하는" },
    { english: "trepidation", korean: "두려움", koreanMeaning: "큰 두려움이나 불안" },
    { english: "undulate", korean: "물결치다", koreanMeaning: "물결처럼 움직이거나 흔들리다" },
    { english: "vociferous", korean: "소리 높여 외치는", koreanMeaning: "크고 단호하게 소리 높여 외치는" },
    { english: "wane", korean: "약해지다", koreanMeaning: "힘, 영향력 등이 약해지다" },
    { english: "abstinence", korean: "절제", koreanMeaning: "어떤 것을 자제하거나 삼가는 행위" },
    { english: "bravado", korean: "허세", koreanMeaning: "두려움을 감추기 위한 과시된 용기" },
    { english: "circumspect", korean: "신중한", koreanMeaning: "위험을 피하기 위해 신중하고 조심하는" },
    { english: "clandestine", korean: "은밀한", koreanMeaning: "비밀스럽게 행해지는" },
    { english: "confluence", korean: "합류", koreanMeaning: "두 가지 이상의 것이 합쳐지는 지점" },
    { english: "desultory", korean: "두서 없는", koreanMeaning: "계획 없이 되는대로 하는, 산만한" },
    { english: "disparate", korean: "이질적인", koreanMeaning: "근본적으로 다른, 비교할 수 없는" },
    { english: "emaciated", korean: "쇠약해진", koreanMeaning: "심하게 마르고 쇠약해진" },
    { english: "fortuitous", korean: "우연한", koreanMeaning: "우연히 일어나는, 행운의" },
    { english: "harrowing", korean: "고통스러운", koreanMeaning: "극도로 고통스럽거나 비참한" },
    { english: "imperious", korean: "오만한", koreanMeaning: "오만하고 지배적인" },
    { english: "incongruous", korean: "어울리지 않는", koreanMeaning: "어울리지 않거나 부조화스러운" },
    { english: "licentious", korean: "방탕한", koreanMeaning: "부도덕하거나 방탕한" },
    { english: "meticulous", korean: "꼼꼼한", koreanMeaning: "매우 세심하고 꼼꼼한" },
    { english: "oscillate", korean: "진동하다", koreanMeaning: "두 지점 사이를 규칙적으로 움직이다" },
    { english: "plethora", korean: "과잉", koreanMeaning: "과도한 양이나 과잉" },
    { english: "precarious", korean: "위태로운", koreanMeaning: "불안정하거나 위험한" },
    { english: "proliferate", korean: "증식하다", koreanMeaning: "빠르게 증가하거나 증식하다" },
    { english: "reproach", korean: "비난하다", koreanMeaning: "불만을 표현하거나 비난하다" },
    { english: "subterfuge", korean: "속임수", koreanMeaning: "목표를 달성하기 위한 속임수나 술책" },
    { english: "superfluous", korean: "불필요한", koreanMeaning: "필요 이상으로 많은, 불필요한" },
    { english: "transient", korean: "일시적인", koreanMeaning: "잠시 동안만 지속되는" },
    { english: "vex", korean: "괴롭히다", koreanMeaning: "짜증나게 하거나 괴롭히다" },
    { english: "vivacious", korean: "활기찬", koreanMeaning: "활기차고 생기 넘치는" },
    { english: "abrogate", korean: "폐지하다", koreanMeaning: "공식적으로 법이나 합의를 폐지하다" },
    { english: "capitulate", korean: "항복하다", koreanMeaning: "조건 없이 항복하다" },
    { english: "conflagration", korean: "대화재", koreanMeaning: "대규모의 파괴적인 화재" },
    { english: "debilitate", korean: "쇠약하게 하다", koreanMeaning: "누군가를 쇠약하게 만들다" },
    { english: "egregious", korean: "지독한", koreanMeaning: "매우 나쁘거나 충격적인" },
    { english: "expedient", korean: "편리한", koreanMeaning: "목적 달성에 편리하지만 반드시 옳지는 않은" },
    { english: "fecund", korean: "비옥한", koreanMeaning: "다작의, 비옥한" },
    { english: "hegemony", korean: "패권", koreanMeaning: "한 국가나 집단의 다른 집단에 대한 지배력" },
    { english: "insidious", korean: "교활한", koreanMeaning: "점진적이고 해로운 방식으로 교활하게 작용하는" },
    { english: "lachrymose", korean: "눈물이 많은", koreanMeaning: "눈물이 많거나 슬픔을 표현하는" },
    { english: "misanthrope", korean: "염세가", koreanMeaning: "인간을 싫어하는 사람" },
    { english: "obstreperous", korean: "시끄러운", koreanMeaning: "시끄럽고 다루기 힘든" },
    { english: "perfidious", korean: "배신하는", koreanMeaning: "배신하거나 믿을 수 없는" },
    { english: "quiescent", korean: "정지한", koreanMeaning: "활동이 없는, 정지한" },
    { english: "reprobate", korean: "타락한 사람", koreanMeaning: "도덕적으로 타락한 사람" },
    { english: "soporific", korean: "최면성의", koreanMeaning: "졸음을 유발하는" },
    { english: "surreptitious", korean: "은밀한", koreanMeaning: "은밀하게 행해지는" },
    { english: "turgid", korean: "과장된", koreanMeaning: "과장되거나 부풀려진" },
    { english: "unctuous", korean: "미끈거리는", koreanMeaning: "지나치게 아첨하거나 진실성이 없는" },
    { english: "venerable", korean: "존경할 만한", koreanMeaning: "많은 존경을 받을 만한" },
    { english: "wizened", korean: "주름진", koreanMeaning: "나이 때문에 주름지고 시든" },
    { english: "zealot", korean: "열광자", koreanMeaning: "열성적이고 타협하지 않는 지지자" },
    { english: "abeyance", korean: "중지", koreanMeaning: "일시적인 중지 또는 보류" },
    { english: "burgeon", korean: "급성장하다", koreanMeaning: "빠르게 성장하거나 번성하다" },
    { english: "debacle", korean: "대실패", koreanMeaning: "갑작스럽고 굴욕적인 실패" },
    { english: "egress", korean: "나가다", koreanMeaning: "나가는 행위 또는 출구" },
    { english: "expunge", korean: "삭제하다", koreanMeaning: "어떤 것을 지우거나 삭제하다" },
    { english: "florid", korean: "화려한", koreanMeaning: "지나치게 화려하거나 장식적인" },
    { english: "hapless", korean: "불운한", koreanMeaning: "불운하거나 불행한" },
    { english: "imbibe", korean: "흡수하다", koreanMeaning: "액체를 마시거나 정보를 흡수하다" },
    { english: "inchoate", korean: "초기 단계의", koreanMeaning: "초기 단계의, 불완전한" },
    { english: "lugubrious", korean: "침울한", koreanMeaning: "슬프거나 침울한" },
    { english: "mendacious", korean: "거짓된", koreanMeaning: "거짓말을 하거나 거짓된 경향이 있는" },
    { english: "obsequious", korean: "아첨하는", koreanMeaning: "지나치게 아첨하거나 비굴한" },
    { english: "penurious", korean: "극빈한", koreanMeaning: "극도로 가난하거나 인색한" },
    { english: "raucous", korean: "시끄러운", koreanMeaning: "거칠고 시끄러운 소리를 내는" },
    { english: "salient", korean: "가장 중요한", koreanMeaning: "가장 눈에 띄거나 중요한" },
    { english: "trenchant", korean: "날카로운", koreanMeaning: "날카롭고 효과적인" },
    { english: "adroit", korean: "능숙한", koreanMeaning: "솜씨가 좋거나 능숙한" },
    { english: "alacrity", korean: "민활함", koreanMeaning: "민첩하고 열성적인 태도" },
    { english: "animosity", korean: "악의", koreanMeaning: "강한 적개심이나 증오심" },
    { english: "apathy", korean: "무관심", koreanMeaning: "흥미나 열정의 결여" },
    { english: "assuage", korean: "달래다", koreanMeaning: "불쾌하거나 강한 감정을 완화시키다" },
    { english: "avarice", korean: "탐욕", koreanMeaning: "과도한 부나 재물에 대한 욕심" },
    { english: "bellicose", korean: "호전적인", koreanMeaning: "싸우거나 논쟁하기를 좋아하는" },
    { english: "belligerent", korean: "적대적인", koreanMeaning: "적대적이거나 공격적인" },
    { english: "candor", korean: "솔직함", koreanMeaning: "솔직하고 정직한 태도" },
    { english: "chastise", korean: "꾸짖다", koreanMeaning: "심하게 꾸짖거나 비난하다" },
    { english: "coalesce", korean: "합치다", koreanMeaning: "서로 합쳐져 하나가 되다" },
    { english: "cogent", korean: "설득력 있는", koreanMeaning: "설득력 있고 타당한" },
    { english: "concomitant", korean: "수반하는", koreanMeaning: "동시에 또는 함께 발생하는" },
    { english: "conflagration", korean: "대화재", koreanMeaning: "대규모의 파괴적인 화재" },
    { english: "contrite", korean: "뉘우치는", koreanMeaning: "깊이 뉘우치고 후회하는" },
    { english: "convoluted", korean: "복잡한", koreanMeaning: "매우 복잡하거나 이해하기 어려운" },
    { english: "credulous", korean: "잘 믿는", koreanMeaning: "너무 쉽게 믿는, 속기 쉬운" },
    { english: "culpable", korean: "유죄의", koreanMeaning: "비난받을 만한, 유죄의" },
    { english: "delineate", korean: "묘사하다", koreanMeaning: "정확하게 묘사하거나 설명하다" },
    { english: "demure", korean: "얌전한", koreanMeaning: "점잖고 조용한" },
    { english: "deprecate", korean: "비난하다", koreanMeaning: "비난하거나 반대하다" },
    { english: "diffident", korean: "소심한", koreanMeaning: "자신감이 부족한, 소심한" },
    { english: "disingenuous", korean: "솔직하지 못한", koreanMeaning: "솔직하지 못하거나 불성실한" },
    { english: "disparage", korean: "폄하하다", koreanMeaning: "하찮게 여기거나 폄하하다" },
    { english: "dogmatic", korean: "독단적인", koreanMeaning: "자신의 의견을 고집하는, 독단적인" },
    { english: "duplicity", korean: "이중성", koreanMeaning: "기만적인 이중성" },
    { english: "ebullient", korean: "활기 넘치는", koreanMeaning: "활기 넘치고 열정적인" },
    { english: "effervescent", korean: "활기 넘치는", koreanMeaning: "활기 넘치고 생기 있는" },
    { english: "egregious", korean: "지독한", koreanMeaning: "매우 나쁘거나 충격적인" },
    { english: "elucidate", korean: "명확히 하다", koreanMeaning: "명확하게 설명하거나 밝히다" },
    { english: "enmity", korean: "적대감", koreanMeaning: "강한 적대감" },
    { english: "equivocate", korean: "얼버무리다", koreanMeaning: "모호하거나 불분명하게 말하다" },
    { english: "exacerbate", korean: "악화시키다", koreanMeaning: "상황을 악화시키다" },
    { english: "exculpate", korean: "무죄를 입증하다", koreanMeaning: "무죄를 입증하거나 책임에서 벗어나게 하다" },
    { english: "exigent", korean: "위급한", koreanMeaning: "매우 긴급하거나 요구가 많은" },
    { english: "fastidious", korean: "꼼꼼한", koreanMeaning: "매우 세심하고 까다로운" },
    { english: "fatuous", korean: "어리석은", koreanMeaning: "어리석거나 멍청한" },
    { english: "gauche", korean: "서투른", koreanMeaning: "사회적으로 서투르거나 어색한" },
    { english: "hackneyed", korean: "진부한", koreanMeaning: "지나치게 사용되어 진부한" },
    { english: "harangue", korean: "장광설", koreanMeaning: "길고 격렬한 연설" },
    { english: "ignominious", korean: "불명예스러운", koreanMeaning: "수치스럽거나 불명예스러운" },
    { english: "impecunious", korean: "무일푼의", koreanMeaning: "돈이 없는, 가난한" },
    { english: "impetuous", korean: "충동적인", koreanMeaning: "충동적으로 행동하거나 생각하는" },
    { english: "inchoate", korean: "초기의", koreanMeaning: "막 시작된, 불완전한" },
    { english: "incontrovertible", korean: "반박할 수 없는", koreanMeaning: "논쟁의 여지가 없는, 반박할 수 없는" },
    { english: "indefatigable", korean: "지칠 줄 모르는", koreanMeaning: "지치지 않는, 끊임없이 노력하는" },
    { english: "insidious", korean: "교활한", koreanMeaning: "서서히 몰래 해를 끼치는" },
    { english: "intransigent", korean: "비타협적인", koreanMeaning: "타협하지 않는, 완고한" },
    { english: "lachrymose", korean: "눈물 많은", koreanMeaning: "눈물이 많거나 슬픔을 표현하는" },
    { english: "lugubrious", korean: "침울한", koreanMeaning: "매우 슬프고 우울한" },
    { english: "mawkish", korean: "징그러운", koreanMeaning: "지나치게 감상적인, 징그러운" },
    { english: "neophyte", korean: "초보자", koreanMeaning: "새로운 활동이나 기술의 초보자" },
    { english: "noisome", korean: "불쾌한", koreanMeaning: "매우 불쾌하거나 불쾌한 냄새가 나는" },
    { english: "obdurate", korean: "고집 센", koreanMeaning: "고집이 세거나 완고한" },
    { english: "obsequious", korean: "아첨하는", koreanMeaning: "지나치게 아첨하거나 비굴한" },
    { english: "onerous", korean: "힘든", koreanMeaning: "부담스럽거나 힘든" },
    { english: "opprobrium", korean: "맹비난", koreanMeaning: "가혹한 비난이나 비판" },
    { english: "ostensibly", korean: "표면상으로는", koreanMeaning: "표면상으로는 또는 겉으로는" },
    { english: "panacea", korean: "만병통치약", koreanMeaning: "모든 질병이나 문제에 대한 해결책" },
    { english: "paradigm", korean: "패러다임", koreanMeaning: "특정 분야의 전형적인 예시나 모델" },
    { english: "paragon", korean: "모범", koreanMeaning: "탁월한 모범이나 완벽한 예시" },
    { english: "penchant", korean: "강한 기호", koreanMeaning: "어떤 것을 강하게 좋아하거나 선호하는 경향" },
    { english: "perfidious", korean: "불성실한", koreanMeaning: "불성실하거나 배신적인" },
    { english: "perfunctory", korean: "성의 없는", koreanMeaning: "열의 없이 형식적으로 하는, 피상적인" },
    { english: "perspicacious", korean: "통찰력 있는", koreanMeaning: "뛰어난 통찰력이나 이해력을 가진" },
    { english: "phlegmatic", korean: "냉담한", koreanMeaning: "냉담하거나 침착한" },
    { english: "platitude", korean: "진부한 말", koreanMeaning: "새롭거나 흥미롭지 않은 진부한 말" },
    { english: "plethora", korean: "과잉", koreanMeaning: "과도한 양이나 과잉" },
    { english: "polemic", korean: "논쟁", koreanMeaning: "강력한 언어 공격이나 비판" },
    { english: "precocious", korean: "조숙한", koreanMeaning: "나이에 비해 이른 발달을 보이는" },
    { english: "predilection", korean: "선호", koreanMeaning: "특정 것에 대한 선호나 편애" },
    { english: "profligate", korean: "방탕한", koreanMeaning: "낭비하거나 무모한" },
    { english: "pugnacious", korean: "싸우기 좋아하는", koreanMeaning: "싸우거나 논쟁하기를 좋아하는" },
    { english: "quandary", korean: "곤경", koreanMeaning: "어려운 상황이나 딜레마" },
    { english: "querulous", korean: "불평하는", koreanMeaning: "불평하거나 투덜거리는 경향이 있는" },
    { english: "rancor", korean: "원한", koreanMeaning: "깊은 악의나 원한" },
    { english: "recalcitrant", korean: "저항하는", koreanMeaning: "권위에 저항하는, 다루기 힘든" },
    { english: "reciprocate", korean: "상호 교환하다", koreanMeaning: "주고받는 행위" },
    { english: "reprobate", korean: "타락한 사람", koreanMeaning: "도덕적으로 타락한 사람" },
    { english: "repudiate", korean: "거부하다", koreanMeaning: "거부하거나 부인하다" },
    { english: "rife", korean: "만연한", koreanMeaning: "흔하거나 널리 퍼져 있는" },
    { english: "salubrious", korean: "건강에 좋은", koreanMeaning: "건강에 좋거나 유익한" },
    { english: "satiate", korean: "만족시키다", koreanMeaning: "충분히 만족시키다" },
    { english: "soporific", korean: "최면성의", koreanMeaning: "졸음을 유발하는" },
    { english: "spurious", korean: "가짜의", koreanMeaning: "진품이 아닌, 가짜의" },
    { english: "stolid", korean: "무감각한", koreanMeaning: "감정을 거의 보이지 않는, 둔감한" },
    { english: "superfluous", korean: "불필요한", koreanMeaning: "필요 이상으로 많은, 불필요한" },
    { english: "surreptitious", korean: "은밀한", koreanMeaning: "은밀하게 행해지는" },
    { english: "tacit", korean: "암묵적인", koreanMeaning: "명시적으로 말하지 않아도 이해되는" },
    { english: "tenuous", korean: "미약한", koreanMeaning: "매우 약하거나 미약한" },
    { english: "tirade", korean: "장황한 비난", koreanMeaning: "길고 격렬한 비난 연설" },
    { english: "transient", korean: "일시적인", koreanMeaning: "잠시 동안만 지속되는" },
    { english: "trenchant", korean: "날카로운", koreanMeaning: "날카롭고 효과적인" },
    { english: "truculent", korean: "공격적인", koreanMeaning: "공격적이거나 호전적인" },
    { english: "ubiquitous", korean: "어디에나 있는", koreanMeaning: "어디에나 존재하거나 나타나는" },
    { english: "unctuous", korean: "미끈거리는", koreanMeaning: "지나치게 아첨하거나 진실성이 없는" },
    { english: "vacillate", korean: "망설이다", koreanMeaning: "결정을 못하고 흔들리다" },
    { english: "vilify", korean: "비방하다", koreanMeaning: "매우 비방하거나 비방하다" },
    { english: "vituperative", korean: "매도하는", koreanMeaning: "가혹하게 비난하거나 매도하는" },
    { english: "wanton", korean: "무자비한", koreanMeaning: "악의적이거나 무자비한" },
    { english: "acrimony", korean: "악감정", koreanMeaning: "말이나 태도에 나타나는 악감정이나 쓰라림" },
    { english: "anomaly", korean: "변칙", koreanMeaning: "예상이나 표준에서 벗어난 것" },
    { english: "antipathy", korean: "반감", koreanMeaning: "깊은 반감이나 혐오감" },
    { english: "apotheosis", korean: "절정", koreanMeaning: "최고의 예시나 절정" },
    { english: "ascetic", korean: "금욕적인", koreanMeaning: "엄격한 자제와 금욕적인 생활을 하는" },
    { english: "assiduous", korean: "근면한", koreanMeaning: "꾸준하고 부지런한" },
    { english: "auspicious", korean: "길조의", koreanMeaning: "좋은 징조를 보이는, 길조의" },
    { english: "avarice", korean: "탐욕", koreanMeaning: "과도한 부나 재물에 대한 욕심" },
    { english: "beguile", korean: "속이다", koreanMeaning: "매력적으로 속이거나 유혹하다" },
    { english: "benevolent", korean: "자비로운", koreanMeaning: "친절하고 너그러운" },
    { english: "blight", korean: "손상시키다", koreanMeaning: "성장을 해치거나 손상시키다" },
    { english: "bombastic", korean: "과장된", koreanMeaning: "과장되거나 허풍스러운" },
    { english: "bucolic", korean: "전원적인", koreanMeaning: "목가적인, 전원적인 삶과 관련된" },
    { english: "burgeoning", korean: "급성장하는", koreanMeaning: "빠르게 성장하거나 번성하는" },
    { english: "cacophony", korean: "불협화음", koreanMeaning: "불쾌한 소리의 조합" },
    { english: "calumny", korean: "비방", koreanMeaning: "명예를 훼손하는 거짓 진술" },
    { english: "candid", korean: "솔직한", koreanMeaning: "솔직하고 숨김없는" },
    { english: "capitulate", korean: "항복하다", koreanMeaning: "조건 없이 항복하다" },
    { english: "charlatan", korean: "사기꾼", koreanMeaning: "자격이 없는데 아는 척하는 사람" },
    { english: "chicanery", korean: "속임수", koreanMeaning: "교활한 속임수나 계략" },
    { english: "clamor", korean: "아우성", koreanMeaning: "크고 혼란스러운 소리" },
    { english: "cogent", korean: "설득력 있는", koreanMeaning: "설득력 있고 타당한" },
    { english: "commensurate", korean: "비례하는", koreanMeaning: "규모나 정도가 비례하는" },
    { english: "compendium", korean: "요약", koreanMeaning: "어떤 주제에 대한 간략한 요약이나 집합" },
    { english: "complaisant", korean: "정중한", koreanMeaning: "기꺼이 다른 사람을 기쁘게 하려는" },
    { english: "concord", korean: "일치", koreanMeaning: "의견이나 행동의 일치" },
    { english: "conflagration", korean: "대화재", koreanMeaning: "대규모의 파괴적인 화재" },
    { english: "conjecture", korean: "추측", koreanMeaning: "정보가 불충분할 때 내리는 추측" },
    { english: "connive", korean: "묵인하다", koreanMeaning: "비밀리에 불법적이거나 해로운 일을 묵인하다" },
    { english: "connoisseur", korean: "감정가", koreanMeaning: "예술이나 음식에 대한 전문가" },
    { english: "consecrate", korean: "신성하게 하다", koreanMeaning: "신성하게 하거나 봉헌하다" },
    { english: "consternation", korean: "깜짝 놀람", koreanMeaning: "갑작스러운 놀라움이나 불안" },
    { english: "contemptuous", korean: "경멸하는", koreanMeaning: "경멸을 표현하는" },
    { english: "contrite", korean: "뉘우치는", koreanMeaning: "깊이 뉘우치고 후회하는" },
    { english: "convoluted", korean: "복잡한", koreanMeaning: "매우 복잡하거나 이해하기 어려운" },
    { english: "corpulent", korean: "비대한", koreanMeaning: "몸집이 크거나 비대한" },
    { english: "coterie", korean: "소그룹", koreanMeaning: "배타적인 소그룹" },
    { english: "debilitate", korean: "쇠약하게 하다", koreanMeaning: "누군가를 쇠약하게 만들다" },
    { english: "decry", korean: "비난하다", koreanMeaning: "공개적으로 비난하거나 깎아내리다" },
    { english: "deferential", korean: "공손한", koreanMeaning: "존경심을 나타내는" },
    { english: "deleterious", korean: "해로운", koreanMeaning: "해로운, 유해한" },
    { english: "delineate", korean: "묘사하다", koreanMeaning: "정확하게 묘사하거나 설명하다" },
    { english: "demagogue", korean: "선동가", koreanMeaning: "대중의 편견을 이용해 권력을 얻는 사람" },
    { english: "denounce", korean: "비난하다", koreanMeaning: "공개적으로 비난하거나 규탄하다" },
    { english: "deprecate", korean: "비난하다", koreanMeaning: "비난하거나 반대하다" },
    { english: "deride", korean: "비웃다", koreanMeaning: "비웃거나 조롱하다" },
    { english: "desiccate", korean: "건조시키다", koreanMeaning: "철저히 건조시키다" },
    { english: "desultory", korean: "두서 없는", koreanMeaning: "계획 없이 되는대로 하는, 산만한" },
    { english: "dichotomy", korean: "양분", koreanMeaning: "두 가지 대조적인 부분이나 사물로 나뉠 때" },
    { english: "didactic", korean: "교훈적인", koreanMeaning: "가르치거나 도덕적인 교훈을 주려는 의도를 가진" },
    { english: "discretion", korean: "재량", koreanMeaning: "자유롭게 판단하고 행동하는 권리" },
    { english: "disparate", korean: "이질적인", koreanMeaning: "근본적으로 다른, 비교할 수 없는" },
    { english: "disseminate", korean: "퍼뜨리다", koreanMeaning: "정보, 지식 등을 널리 퍼뜨리다" },
    { english: "dissonance", korean: "불협화음", koreanMeaning: "의견이나 생각의 불일치" },
    { english: "divisive", korean: "분열을 초래하는", koreanMeaning: "불화나 분열을 일으키는" },
    { english: "docile", korean: "유순한", koreanMeaning: "순종적이고 다루기 쉬운" },
    { english: "dogmatic", korean: "독단적인", koreanMeaning: "자신의 의견을 고집하는, 독단적인" },
    { english: "dubious", korean: "의심스러운", koreanMeaning: "의심스럽거나 미심쩍은" },
    { english: "duplicity", korean: "이중성", koreanMeaning: "기만적인 이중성" },
    { english: "eclectic", korean: "다방면의", koreanMeaning: "다양한 원천에서 가져온" },
    { english: "efficacious", korean: "효과적인", koreanMeaning: "원하는 결과를 얻는 데 효과적인" },
    { english: "effrontery", korean: "뻔뻔스러움", koreanMeaning: "뻔뻔스럽거나 무례한 태도" },
    { english: "egregious", korean: "지독한", koreanMeaning: "매우 나쁘거나 충격적인" },
    { english: "elicit", korean: "끌어내다", koreanMeaning: "정보나 반응을 끌어내다" },
    { english: "eloquence", korean: "웅변", koreanMeaning: "유창하고 설득력 있는 말" },
    { english: "embezzlement", korean: "횡령", koreanMeaning: "자금을 횡령하는 행위" },
    { english: "emollient", korean: "진정시키는", koreanMeaning: "피부를 부드럽게 하거나 진정시키는" },
    { english: "enervate", korean: "기력을 잃게 하다", koreanMeaning: "기력을 약화시키거나 에너지를 고갈시키다" },
    { english: "enfranchise", korean: "참정권을 주다", koreanMeaning: "시민권이나 참정권을 주다" },
    { english: "ephemeral", korean: "덧없는", koreanMeaning: "지속 시간이 매우 짧은, 덧없는" },
    { english: "exacerbate", korean: "악화시키다", koreanMeaning: "상황이나 문제를 악화시키다" },
    { english: "exasperation", korean: "격분", koreanMeaning: "극도의 짜증이나 격분" },
    { english: "exorbitant", korean: "터무니없는", koreanMeaning: "지나치게 많거나 터무니없는" },
    { english: "expedient", korean: "편리한", koreanMeaning: "목적 달성에 편리하지만 반드시 옳지는 않은" },
    { english: "extol", korean: "칭찬하다", koreanMeaning: "열렬히 칭찬하다" },
    { english: "extricate", korean: "해방시키다", koreanMeaning: "어려운 상황에서 해방시키거나 벗어나게 하다" },
    { english: "fecund", korean: "비옥한", koreanMeaning: "다작의, 비옥한" },
    { english: "feckless", korean: "무책임한", koreanMeaning: "무책임하거나 무능한" },
    { english: "fetter", korean: "구속하다", koreanMeaning: "움직임이나 발전을 제한하거나 구속하다" },
    { english: "fiasco", korean: "대실패", koreanMeaning: "완전하고 굴욕적인 실패" },
    { english: "fledgling", korean: "초보자", koreanMeaning: "경험이 적거나 갓 시작한 사람/단체" },
    { english: "flout", korean: "경멸하다", koreanMeaning: "법이나 규칙을 경멸하거나 어기다" },
    { english: "forestall", korean: "미연에 방지하다", koreanMeaning: "미리 행동하여 방지하거나 가로막다" },
    { english: "fortuitous", korean: "우연한", koreanMeaning: "우연히 일어나는, 행운의" },
    { english: "garrulous", korean: "수다스러운", koreanMeaning: "매우 수다스러운" },
    { english: "germane", korean: "적절한", koreanMeaning: "관련성이 있거나 적절한" },
    { english: "grandiloquent", korean: "과장된", koreanMeaning: "과장되거나 거창한 언어를 사용하는" },
    { english: "gregarious", korean: "사교적인", koreanMeaning: "사람들과 어울리기 좋아하는, 사교적인" },
    { english: "haggard", korean: "초췌한", koreanMeaning: "피곤함, 걱정, 배고픔 등으로 인해 초췌해 보이는" },
    { english: "harbinger", korean: "선구자", koreanMeaning: "다가올 일의 징조나 선구자" },
    { english: "ignominious", korean: "불명예스러운", koreanMeaning: "수치스럽거나 불명예스러운" }
];